services:
  dyalog:
    image: dyalog/dyalog:20.0
    ports:
      - "8888:8888"
      - "4502:4502"
    environment:
      RIDE_INIT: "http:*:8888"
      LOAD: "/workspace/scripts/cloudBootstrap.aplf"
      LD_LIBRARY_PATH: "/workspace/lib"
    volumes:
      - ..:/workspace:rw
    working_dir: /workspace
    restart: unless-stopped
